version: "3"
services:

  mongo:
    image: mongo:4.2.6
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3.8.3-management-alpine
    ports:
      - 127.0.0.1:1883:1883
      - 127.0.0.1:5672:5672
      - 127.0.0.1:8883:8883
      - 127.0.0.1:15672:15672
    volumes:
      - ./environment/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./environment/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./environment/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongo_data:
  rabbitmq_data:
